# Generated by Django 5.1.1 on 2024-10-02 08:37

import user_management.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_management.models.UserManager()),
            ],
        ),
    ]
