# Generated by Django 5.1.1 on 2024-10-02 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_info',
            name='block_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Property_info',
            fields=[
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(max_length=200)),
                ('property_name', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=20)),
                ('unit_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Penthouse', 'Penthouse'), ('Shop', 'Shop')], max_length=20)),
                ('unit_number', models.CharField(max_length=50)),
                ('floor_number', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('number_of_bedrooms', models.PositiveIntegerField()),
                ('number_of_bathrooms', models.PositiveIntegerField()),
                ('balconies_or_patio_size', models.CharField(blank=True, max_length=50)),
                ('parking_space_details', models.CharField(blank=True, max_length=100)),
                ('number_of_halls', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('size_in_sqm', models.FloatField()),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_information.block_info')),
            ],
        ),
    ]
