# Generated by Django 5.1.1 on 2024-10-07 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0002_alter_block_info_block_name_property_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('amenity_id', models.AutoField(primary_key=True, serialize=False)),
                ('amenity_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('pro_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_number', models.IntegerField(unique=True)),
                ('property_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('unit_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_number', models.IntegerField(unique=True)),
                ('unit_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='property_info',
            name='balconies_or_patio_size',
        ),
        migrations.RemoveField(
            model_name='property_info',
            name='location',
        ),
        migrations.RemoveField(
            model_name='property_info',
            name='parking_space_details',
        ),
        migrations.RemoveField(
            model_name='property_info',
            name='unit_number',
        ),
        migrations.AddField(
            model_name='property_info',
            name='area_type',
            field=models.CharField(blank=True, choices=[('SQFT', 'Square Feet (SQFT)'), ('MARLA', 'Marla'), ('KANAL', 'Kanal')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property_info',
            name='area_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property_info',
            name='balcony_or_patio',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='property_info',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property_info',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property_info',
            name='parking_space',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
        migrations.AddField(
            model_name='property_info',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='property_info',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='size_in_sqm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property_info',
            name='amenity_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='All_information.amenity'),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_information.propertytype'),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='unit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_information.unittype'),
        ),
    ]
