# Generated by Django 5.1.2 on 2024-10-19 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0004_owner_service_property_info_document_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_profile_picture', models.ImageField(blank=True, null=True, upload_to='tenant_profiles/')),
                ('tenant_phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('tenant_email', models.EmailField(max_length=254, unique=True)),
                ('tenant_cnic', models.CharField(max_length=15)),
                ('tenant_address', models.TextField()),
                ('tenant_country', models.CharField(max_length=100)),
                ('tenant_city', models.CharField(max_length=100)),
                ('starting_date', models.DateField()),
                ('ending_agreement_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_monthly_utility_charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agreement_attachment', models.FileField(blank=True, null=True, upload_to='agreements/')),
                ('assign_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_information.property_info')),
            ],
        ),
    ]
