# Generated by Django 5.1.2 on 2024-10-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0005_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_guardian_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
