# Generated by Django 5.1.2 on 2024-10-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0006_tenant_tenant_guardian_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaType',
            fields=[
                ('area_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('area_type_name', models.CharField(max_length=100)),
                ('area_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
