# Generated by Django 5.1.2 on 2024-10-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0008_remove_propertytype_joint_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatype',
            name='area_type_name',
            field=models.CharField(blank=True, choices=[('SQFT', 'Square Feet (SQFT)'), ('MARLA', 'Marla'), ('KANAL', 'Kanal')], max_length=10, null=True),
        ),
    ]
