# Generated by Django 5.1.2 on 2024-10-22 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0009_alter_areatype_area_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_info',
            name='area_type',
        ),
        migrations.RemoveField(
            model_name='property_info',
            name='area_value',
        ),
        migrations.AddField(
            model_name='property_info',
            name='property_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='All_information.areatype'),
        ),
    ]
