# Generated by Django 5.1.2 on 2024-10-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0010_remove_property_info_area_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsSetup',
            fields=[
                ('bill_setup_id', models.AutoField(primary_key=True, serialize=False)),
                ('charges', models.JSONField()),
                ('property_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_setups', to='All_information.areatype')),
                ('property_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_setups', to='All_information.property_info')),
                ('property_type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_setups', to='All_information.propertytype')),
            ],
        ),
    ]
