# Generated by Django 5.1.2 on 2024-10-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0015_alter_managementcommittee_mc_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCost',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_title', models.CharField(max_length=200)),
                ('m_date', models.DateField()),
                ('m_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('m_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
