# Generated by Django 5.1.1 on 2024-11-27 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0016_maintenancecost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=255, unique=True)),
                ('form_fields', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='billssetup',
            old_name='charges',
            new_name='form_data',
        ),
        migrations.AddField(
            model_name='billssetup',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='All_information.formbuilder'),
        ),
    ]
