# Generated by Django 5.1.1 on 2024-11-27 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0017_formbuilder_rename_charges_billssetup_form_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billssetup',
            name='property_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills_setups', to='All_information.property_info'),
        ),
    ]
