# Generated by Django 5.1.2 on 2024-11-29 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0017_formbuilder_rename_charges_billssetup_form_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billssetup',
            name='property_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills_setups', to='All_information.property_info'),
        ),
        migrations.CreateModel(
            name='PaymentsCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(blank=True, max_length=255, null=True)),
                ('select_month_year_date', models.DateField()),
                ('total_bills_due', models.JSONField()),
                ('total_bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('block_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='All_information.block_info')),
                ('property_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='All_information.property_info')),
            ],
        ),
    ]
