# Generated by Django 5.1.1 on 2024-12-27 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0018_alter_billssetup_property_number_paymentscollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentscollection',
            name='select_month_year_date',
        ),
        migrations.RemoveField(
            model_name='paymentscollection',
            name='total_bill',
        ),
        migrations.RemoveField(
            model_name='paymentscollection',
            name='total_bills_due',
        ),
        migrations.AddField(
            model_name='paymentscollection',
            name='bills_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentscollection',
            name='month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentscollection',
            name='payments_collection_mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentscollection',
            name='total_cuttent_bills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentscollection',
            name='year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentscollection',
            name='block_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_information.block_info'),
        ),
        migrations.AlterField(
            model_name='paymentscollection',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paymentscollection',
            name='property_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
