# Generated by Django 5.1.1 on 2025-01-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0018_alter_billssetup_property_number'),
        ('All_information', '0019_remove_paymentscollection_select_month_year_date_and_more'),
    ]

    operations = [
    ]
