# Generated by Django 5.1.1 on 2025-01-01 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0020_merge_20250101_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentscollection',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='All_information.formbuilder'),
        ),
    ]
