# Generated by Django 5.1.1 on 2025-01-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0021_paymentscollection_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentscollection',
            old_name='form',
            new_name='form_id',
        ),
    ]
