# Generated by Django 5.1.1 on 2025-01-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0022_rename_form_paymentscollection_form_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentscollection',
            old_name='form_id',
            new_name='form',
        ),
    ]
