# Generated by Django 5.2.3 on 2025-06-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0023_rename_form_id_paymentscollection_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentscollection',
            name='balance',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentscollection',
            name='bill_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
