# Generated by Django 5.2.3 on 2025-06-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0024_paymentscollection_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentscollection',
            old_name='total_cuttent_bills',
            new_name='total_current_bills',
        ),
    ]
