# Generated by Django 5.2.3 on 2025-06-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0025_rename_total_cuttent_bills_paymentscollection_total_current_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentscollection',
            name='currect_balance',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
