# Generated by Django 5.2.3 on 2025-06-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0026_paymentscollection_currect_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentscollection',
            name='paid_amount',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
