# Generated by Django 5.2.3 on 2025-06-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0027_paymentscollection_paid_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', models.DecimalField(decimal_places=2, help_text='Fine percentage, e.g., 10 for 10%', max_digits=5)),
            ],
        ),
    ]
