# Generated by Django 5.2.3 on 2025-06-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0028_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='fine',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
