# Generated by Django 5.2.3 on 2025-07-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0032_alter_owner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
