# Generated by Django 5.2.3 on 2025-07-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0033_owner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerproperty',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='ownerproperty',
            name='property_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_owners', to='All_information.property_info'),
        ),
    ]
