# Generated by Django 5.2.3 on 2025-07-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0034_ownerproperty_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerproperty',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_information.owner'),
        ),
        migrations.AlterField(
            model_name='ownerproperty',
            name='property_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_information.property_info'),
        ),
    ]
