# Generated by Django 5.2.3 on 2025-07-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0035_alter_ownerproperty_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_info',
            name='owner',
        ),
        migrations.AddField(
            model_name='property_info',
            name='properties',
            field=models.ManyToManyField(related_name='owners', through='All_information.OwnerProperty', to='All_information.property_info'),
        ),
    ]
