# Generated by Django 5.2.3 on 2025-07-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0036_remove_property_info_owner_property_info_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerproperty',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
