# Generated by Django 5.2.3 on 2025-07-08 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0037_ownerproperty_assigned_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_info',
            name='properties',
        ),
    ]
