# Generated by Django 5.2.3 on 2025-07-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0038_remove_property_info_properties'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property_info',
            unique_together={('property_number', 'joint_number')},
        ),
    ]
