# Generated by Django 5.2.3 on 2025-07-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0039_alter_property_info_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_info',
            name='property_number',
            field=models.IntegerField(null=True),
        ),
    ]
