# Generated by Django 5.2.3 on 2025-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0040_alter_property_info_property_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_info',
            name='property_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
