# Generated by Django 5.2.3 on 2025-07-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0041_alter_property_info_property_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basement', 'Basement'), ('Ground Floor', 'Ground Floor'), ('Mezzanine', 'Mezzanine'), ('1st Floor', '1st Floor'), ('2nd Floor', '2nd Floor'), ('3rd Floor', '3rd Floor')], max_length=50, unique=True)),
            ],
        ),
    ]
