# Generated by Django 5.2.3 on 2025-07-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0042_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_info',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='All_information.floor'),
        ),
    ]
