# Generated by Django 5.2.3 on 2025-07-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0043_property_info_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_info',
            name='floor_number',
        ),
    ]
