# Generated by Django 5.2.3 on 2025-07-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0044_remove_property_info_floor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='billssetup',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills_setups', to='All_information.floor'),
        ),
    ]
