# Generated by Django 5.2.3 on 2025-07-17 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0045_billssetup_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_current_bills', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_bills', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_by', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('online', 'Online')], max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=255, null=True)),
                ('after_pay_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payment_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reports', to='All_information.paymentscollection')),
            ],
        ),
    ]
