# Generated by Django 5.2.3 on 2025-07-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0046_paymentreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreport',
            name='balance',
        ),
    ]
