# Generated by Django 5.2.3 on 2025-07-17 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0047_remove_paymentreport_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentreport',
            old_name='paid_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='paymentreport',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentreport',
            name='after_pay_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paymentreport',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentreport',
            name='payment_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentreport',
            name='payment_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='All_information.paymentscollection'),
        ),
        migrations.AlterField(
            model_name='paymentreport',
            name='received_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paymentreport',
            name='total_bills',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paymentreport',
            name='total_current_bills',
            field=models.FloatField(),
        ),
    ]
