# Generated by Django 5.2.3 on 2025-07-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0048_rename_paid_at_paymentreport_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentreport',
            old_name='created_at',
            new_name='paid_date',
        ),
    ]
