# Generated by Django 5.2.3 on 2025-07-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0049_rename_created_at_paymentreport_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
