# Generated by Django 5.2.3 on 2025-07-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0050_alter_floor_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property_info',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='property_info',
            name='any_note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='property_number',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='property_info',
            name='city',
        ),
        migrations.RemoveField(
            model_name='property_info',
            name='country',
        ),
        migrations.RemoveField(
            model_name='property_info',
            name='joint_number',
        ),
        migrations.RemoveField(
            model_name='property_info',
            name='size_in_sqm',
        ),
        migrations.RemoveField(
            model_name='property_info',
            name='status',
        ),
    ]
