# Generated by Django 5.2.3 on 2025-07-31 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0052_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_info',
            name='property_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='All_information.currency'),
        ),
    ]
