# Generated by Django 5.2.3 on 2025-07-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0053_alter_property_info_property_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_info',
            name='property_value',
        ),
    ]
