# Generated by Django 5.2.3 on 2025-07-31 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0054_remove_property_info_property_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_info',
            name='property_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='All_information.currency'),
        ),
    ]
