# Generated by Django 5.2.3 on 2025-07-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0055_property_info_property_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_info',
            name='amenity_name',
        ),
        migrations.AddField(
            model_name='property_info',
            name='amenity_name',
            field=models.ManyToManyField(blank=True, to='All_information.amenity'),
        ),
    ]
