# Generated by Django 5.2.3 on 2025-07-31 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0056_remove_property_info_amenity_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property_info',
            name='document_attachment',
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='All_information.property_info')),
            ],
        ),
    ]
