# Generated by Django 5.2.3 on 2025-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0057_remove_property_info_document_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='secondary_owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='third_owner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
