# Generated by Django 5.2.3 on 2025-08-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0058_owner_secondary_owner_owner_third_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentscollection',
            name='monthly_rent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
