# Generated by Django 5.2.3 on 2025-08-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0060_ownerproperty_user_tenant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerproperty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='user',
        ),
    ]
