# Generated by Django 5.2.3 on 2025-08-04 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0061_remove_ownerproperty_user_remove_tenant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user_id',
        ),
        migrations.AddField(
            model_name='complaint',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='All_information.owner'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='All_information.tenant'),
        ),
    ]
