# Generated by Django 5.2.3 on 2025-08-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0062_remove_complaint_user_id_complaint_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Inactive', max_length=10),
        ),
    ]
