# Generated by Django 5.2.3 on 2025-08-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0063_currency_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_info',
            name='amenity_name',
            field=models.ManyToManyField(blank=True, null=True, to='All_information.amenity'),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='building_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='number_of_bedrooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='number_of_halls',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property_info',
            name='property_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
