# Generated by Django 5.2.3 on 2025-08-27 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('All_information', '0064_alter_property_info_amenity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_info',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='All_information.unittype'),
        ),
    ]
